
/***************************************************************************
 ***************************************************************************
 ***************************************************************************
 *****
 ***** Welcome!
 *****
 ***** This file is part of the BeeSoft robot control software.
 ***** The version number is:
 *****
 *****                  v1.3.8 (released Aug 5, 1998)
 *****                  this is not an official BeeSoft version
 *****
 ***** Please refer to bee/src/COPYRIGHT for copyright and liability
 ***** information.
 *****
 ***************************************************************************
 ***************************************************************************
 ***************************************************************************/



/*
 * IMPORTANT NOTICE: Do not edit this file!!!
 *
 *                   This file contains the actual version number
 *                   of the software contained in the current
 *                   directory. 
 */


/* --------------------------------------------------
 *
 * MAJOR VERSION NUMBER
 *
 */

#define	  BEESOFT_VERSION_MAJOR 1
/* --------------------------------------------------
 *
 * MINOR VERSION NUMBER
 *
 */

#define   BEESOFT_VERSION_MINOR 3

/* --------------------------------------------------
 *
 * DATE
 *
 */

#define   BEESOFT_VERSION_DATE "Aug 5, 1998"

/* --------------------------------------------------
 *
 * ROBOT TYPE
 *
 */

#ifdef B21
#define	  BEESOFT_VERSION_ROBOT_TYPE 21
#else
#define	  BEESOFT_VERSION_ROBOT_TYPE 14
#endif
